import Foundation

/// Wrapper-process parser for `livesh --open <sh_id>` bridges. Mirrors `TmuxResumeParser` but
/// emits bindings tagged `kind: "livesh"` so the rest of the resume pipeline
/// (`Workspace.effectiveSurfaceResumeBinding`, `LiveShellChildExitHandler`,
/// `palette.killFocusedLiveShell`) can recognize them.
///
/// Detection contract: livesh self-reexecs to `livesh --open <sh_id>` after creating a daemon
/// shell. The bridge process therefore carries the session id in its argv, which is what we
/// match here. The id is treated as the resume checkpoint so cmux restart → `livesh --open <id>`
/// reattaches the same daemon-owned shell instead of forking a new one.
enum LiveShellResumeParser {
    static func binding(
        processName: String,
        processPath: String?,
        arguments: [String],
        environment: [String: String],
        capturedAt: TimeInterval
    ) -> SurfaceResumeBindingSnapshot? {
        let observed = ObservedLiveshProcess(
            processName: processName,
            processPath: processPath,
            arguments: arguments
        )
        guard observed.isLiveshProcess,
              let sessionId = liveshSessionId(in: observed.arguments),
              isSafeSessionID(sessionId) else {
            return nil
        }
        let executable = liveshExecutable(observed: observed)
        let argv = [executable, "--open", sessionId]
        let command = argv.map(shellSingleQuoted).joined(separator: " ")
        let cwd = normalized(environment["CMUX_AGENT_LAUNCH_CWD"] ?? environment["PWD"])
        return SurfaceResumeBindingSnapshot(
            name: "livesh \(sessionId)",
            kind: "livesh",
            command: command,
            cwd: cwd,
            checkpointId: sessionId,
            source: "process-detected",
            environment: nil,
            autoResume: true,
            updatedAt: capturedAt
        )
    }

    static func argumentLooksLikeLivesh(_ argument: String) -> Bool {
        let normalized = argument.lowercased()
        let pathComponents = (normalized as NSString).pathComponents
        let basename = pathComponents.last ?? normalized
        return basename == "livesh"
    }

    private struct ObservedLiveshProcess {
        let processName: String
        let processPath: String?
        let arguments: [String]

        var executableBasenames: [String] {
            var names: [String] = []
            if !processName.isEmpty { names.append(processName) }
            if let processPath, !processPath.isEmpty {
                names.append((processPath as NSString).lastPathComponent)
            }
            if let first = arguments.first, !first.isEmpty {
                names.append((first as NSString).lastPathComponent)
            }
            var seen = Set<String>()
            return names.filter { seen.insert($0).inserted }
        }

        var isLiveshProcess: Bool {
            executableBasenames.contains(where: LiveShellResumeParser.argumentLooksLikeLivesh)
        }
    }

    private static func liveshExecutable(observed: ObservedLiveshProcess) -> String {
        if let first = normalized(observed.arguments.first),
           argumentLooksLikeLivesh(first) {
            return first
        }
        if let path = normalized(observed.processPath),
           argumentLooksLikeLivesh(path) {
            return path
        }
        return "livesh"
    }

    private static func liveshSessionId(in arguments: [String]) -> String? {
        var index = 0
        while index < arguments.count {
            let argument = arguments[index]
            if argument == "--open" {
                let valueIndex = index + 1
                guard valueIndex < arguments.count else { return nil }
                return normalized(arguments[valueIndex])
            }
            let prefix = "--open="
            if argument.hasPrefix(prefix) {
                return normalized(String(argument.dropFirst(prefix.count)))
            }
            index += 1
        }
        return nil
    }

    /// Session ids generated by liveshd ought to be `sh_<uuid>`-shaped, but be permissive
    /// (allow letters, digits, `.`, `_`, `-`) while rejecting anything with shell metacharacters
    /// or whitespace — we will feed this into a shell command via `--open {{sessionId}}` so it
    /// must not be able to break out of the argument.
    private static func isSafeSessionID(_ value: String) -> Bool {
        guard !value.isEmpty, value.count <= 128 else { return false }
        return value.range(of: #"^[A-Za-z0-9._-]+$"#, options: .regularExpression) != nil
    }

    private static func normalized(_ rawValue: String?) -> String? {
        guard let rawValue = rawValue?.trimmingCharacters(in: .whitespacesAndNewlines),
              !rawValue.isEmpty else {
            return nil
        }
        return rawValue
    }

    private static func shellSingleQuoted(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
